version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Installing dependencies...
      - pip install --upgrade pip
      - pip install pytest
  pre_build:
    commands:
      - echo Preparing for build...
  build:
    commands:
      - echo Running tests...
      - pytest lambda_functions/test_lambda_function_1.py
