version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install beautifulsoup4
  pre_build:
    commands:
      - echo "Validando o HTML..."
  build:
    commands:
      - pytest test_html.py
artifacts:
  files:
    - index.html
